import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClerkProvider, UserButton,ClerkLoading } from '@clerk/nextjs'
import { auth } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const {userId} = auth()
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
            <ClerkLoading>
              <div className="absolute h-full w-full z-20 backdrop-blur-md animate-pulse bg-transparent flex items-center justify-center top-0 left-0">
                <span className="rounded-full w-10 h-10 border-4 border-black border-t-transparent animate-spin "/>
              </div>
            </ClerkLoading>
            <nav className="flex justify-between items-center bg-slate-300 p-4 ">
              <h1 className="text-xl font-bold tracking-tighter cursor-pointer"><Link href="/">Pendora AI</Link></h1>
              <div className="flex gap-4">
                {!userId? (
                  <>
                    <button className="p-2 rounded bg-slate-950 text-white"><Link href="/sign-in">SignIn</Link></button>
                    <button className="p-2 rounded bg-slate-950 text-white"><Link href="/sign-up">SignUp</Link></button>
                  </>
                ): (
                  <UserButton afterSignOutUrl="/"/>
                )}
              </div>
            </nav>
          <div className="flex min-h-screen flex-col items-center p-24">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
